### PR TITLE
Dev diagnosis hibernate server side

### PR DESCRIPTION
**Pull request by janam1003**
Merge into server side with DiagnosisServerSide

### CODE REVIEW

**Comment by BBonLLo** [comment]
Resolve them Zuli

**Comment by Zuliyaki** [comment]
Resolving them now in class ;) :3

**Comment by Zuliyaki** [comment]
done

**Comment by hhellyeahh** [comment]
ok

**Comment by BBonLLo** [comment]
ok

**Comment by janam1003** [comment]
okay

**Pull request merged**
